apiVersion: my.api.group/v1alpha1
kind: MyAppResource
metadata:
  labels:
    app.kubernetes.io/name: myappresource
    app.kubernetes.io/instance: myappresource-sample
    app.kubernetes.io/part-of: podinfo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: podinfo
  name: myappresource-sample
spec:
  replicaCount: 2
  resources:
    memoryLimit: 64Mi
    cpuRequest: 100m
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: 6.3.6
  ui:
    color: "this is not a color"
    message: "Howdy!"
  redis:
    enabled: true
