name: Podinfo-Operator
run-name: ${{ github.actor }} is working
on: [push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Check Cluster
      run: kubect get pods -A
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: docker-build
      run: make docker-build
    - name: deploy
      run: make deploy
    - name: listpods
      run: kubectl get pod -A
    - name: myappresource
      run: kubectl apply -f ./config/samples/my_v1alpha1_myappresource.yaml
    - name: listpodsagain
      run: kubectl get pod -A
    - name: delete crd
      run: kubectl delete myappresources.my.api.group myappresource-sample
    - name: listpodsagain2
      run: kubectl get pod -A
    - name: remove operator
      run: make undeploy
    - name: listpodsagain3
      run: kubectl get pod -A
    
